language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: TEST_TYPE=prcheck
    - python: 3.3
      env: TEST_TYPE=test
    - python: 3.4
      env: TEST_TYPE=test
    - python: 3.5
      env: TEST_TYPE=test
    - python: 3.6
      env: TEST_TYPE=prcheck
    - python: 3.6
      env: TEST_TYPE=coverage
install:
  - pip install -r requirements-dev.txt
  - pip install -e .
script:
  - make $TEST_TYPE
after_success:
  - if [[ $TEST_TYPE == 'coverage' ]]; then pip install codecov==2.0.5 && codecov; fi
